### ISSUE TITLE
Realsense with Python3

### ISSUE THREAD

**Issue by far-command-man** [IntelRealSense/meta-intel-realsense#20] opened 2020-03-02 03:45 UTC
Hi @srware ,
After your last commit, it is now possible to use T265/D435 with C++ code properly. However, I recently ran into a new issue. I follow the instructions given in README to add Python3 support in my image. I can import pyrealsense2 without any issue but it runs into an error once I declare RealSense sensor pipeline such as **pipe = rs.pipeline()**. It says AttributeError: module 'pyrealsense2' has no attribute 'pipeline'.
I saw this issue https://github.com/IntelRealSense/librealsense/issues/4483#issuecomment-523397651 . The error messages we have looks the same but I am not sure how to resolve it in Yocto. Any help from your side is much appreciated.

**Comment by srware** [comment] 2020-03-02 11:18
Hi @far-command-man,

Thanks for flagging this. The problem is actually directory structure related. The python libs install to "/usr/lib/python3.x/site-packages/pyrealsense2" which isn't in the PYTHON_PATH. If the libs are moved up one level to "site-packages" everything works as expected.

I will get it fixed!

Thanks.

**Comment by far-command-man** [comment] 2020-03-03 06:04
@srware I checked out the "/usr/lib/python3.x/site-packages/pyrealsense2" and found pyrealsense shared object libraries there. I placed them under site-packages/ directory now everything works fine but of course the best way is to get them installed in respective directory originally. Thanks for the help! :)

**Comment by srware** [comment] 2020-03-03 13:40
Should be fixed now.

Thanks.

**Closed by srware** 2020-03-03 13:40 UTC

**Comment by tpwrules** [comment] 2020-07-16 17:00
I'm not sure this is the correct solution to the problem. Putting the shared libraries in site-packages can (although is unlikely to) interfere with other packages. The correct solution would be to copy the wrappers/python/pyrealsense2/__init__.py into the <etc>/site-packages/pyrealsense2 directory, along with the shared libraries. I'm not sure why that doesn't happen by default.

**Comment by persalteas** [comment] 2020-09-04 14:29
Hi, thanks tpwrules, this worked.

After compiling librealsense with (using cmake .. -DBUILD_PYTHON_BINDINGS:bool=true), i had the same issue when importing pyrealsense2 in python3.

However, your package is not necessarily in site-packages. You need to first identify where your pyrealsense2 is:
` python3
>> import pyrealsense2 as rs
>> rs.__path__
['/usr/lib/python3/dist-packages/pyrealsense2']`

Then copy the __init__.py file in your package's folder:

`sudo cp ~/librealsense/wrapper/python/pyrealsense2/__init__.py /usr/lib/python3/dist-packages/pyrealsense2/` solved it for me.

**Comment by lorepieri8** [comment] 2020-09-16 13:44
@peralteas instructions worked for me, there is a typo in his last line though:

`sudo cp ~/librealsense/wrappers/python/pyrealsense2/__init__.py /usr/lib/python3/dist-packages/pyrealsense2/`

**Comment by edwin9610** [comment] 2020-11-06 21:38
@persalteas 
Hello! I did the following but this error appeared. Do you know how to solve it?

>>> import pyrealsense2 as rs
>>> rs.__path__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyrealsense2' has no attribute '__path__'

**Comment by persalteas** [comment] 2020-11-07 14:41
Hi edwin,
it's not `rs.path`, it's `rs.__path__`, try again with the double underscores.

**Comment by edwin9610** [comment] 2020-11-08 14:29
I did that with the double underscores. It's just that when I copied it here it disappeared.

**Comment by srware** [comment] 2020-11-09 14:37
@edwin9610 , I just tried to replicate this building an image from 'master' but it worked fine for me. I am assuming the pyrealsense2 library is being found in the path given it doesn't fail at the import stage.

I have now incorporated the recommendations in this thread into the master branch so maybe give it another go.

Thanks.

**Comment by edwin9610** [comment] 2020-11-26 22:34
@srware Hi, sorry for the late reply.

I have these directories to the path.

jetson@jetson-desktop:~$ python -c "import sys; print(sys.path)"
['', '/home/jetson', '/usr/local/lib', '/usr/local/lib/python3.6/pyrealsense2', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-aarch64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/gtk-2.0']

as shown in the following screenshots.

![screenshot](https://user-images.githubusercontent.com/74073398/100395021-8f4a0d80-303f-11eb-806b-6097cfbf644e.png)
![screenshot_1](https://user-images.githubusercontent.com/74073398/100395023-9113d100-303f-11eb-8a30-a3ab619d1a5f.png)

But I still have the problem with this:
rs.__path__
Traceback (most recent call last):
File "", line 1, in
AttributeError: module 'pyrealsense2' has no attribute 'path'

What should I do now?

**Comment by punchnami** [comment] 2021-01-05 06:52
I'm getting the same error as @edwin9610 , is there any solution?

Thank you in advance!

**Comment by persalteas** [comment] 2021-01-05 09:16
In @edwin9610 's case, since the `__init__.py` file is present in the pyrealsense2 folder, i think the problem is that `/usr/local/lib/python3.6` is not in the path (the list you provided).

@punchnami do you have the package installed somewhere ? Check that the folder contains that `__init__.py` file (or copy it from as i indicated earlier). If yes, check that your package folder is in Python's path.

**Comment by punchnami** [comment] 2021-01-06 02:34
> In @edwin9610 's case, since the `__init__.py` file is present in the pyrealsense2 folder, i think the problem is that `/usr/local/lib/python3.6` is not in the path (the list you provided).
> 
> @punchnami do you have the package installed somewhere ? Check that the folder contains that `__init__.py` file (or copy it as i indicated earlier). If yes, check that your package folder is in Python's path.

Thank you @persalteas , I will check it out!

**Comment by christianschmitzuni** [comment] 2023-12-28 14:25
After "sudo cp ~/librealsense/wrappers/python/pyrealsense2/__init__.py /usr/lib/python3.6/dist-packages/pyrealsense2/" and then copying the additional 6 .so files into /usr/lib/python3.6/dist-packages/pyrealsense2/ aswell

When using import pyrealsense2 I still get the following error:

>>> import pyrealsense2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/dist-packages/pyrealsense2/__init__.py", line 2, in <module>
    from .pyrealsense2 import *
ModuleNotFoundError: No module named 'pyrealsense2.pyrealsense2'
>>> 

Anything that I am missing?
